# Generated by Django 2.0.5 on 2018-05-12 05:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('momotaro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Momotaro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=255, verbose_name='目標')),
                ('limit', models.CharField(max_length=20, verbose_name='期限')),
                ('reason', models.CharField(max_length=255, null=True, verbose_name='目標を設定した理由')),
                ('additional_comments', models.TextField(max_length=500, null=True, verbose_name='自由記入欄')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='text',
        ),
        migrations.AddField(
            model_name='user',
            name='additional_comments',
            field=models.TextField(max_length=500, null=True, verbose_name='自由記入欄'),
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.CharField(max_length=3, null=True, verbose_name='年齢'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=10, null=True, verbose_name='性別'),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=30, null=True, verbose_name='パスワード'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='メールアドレス'),
        ),
    ]
