# Generated by Django 2.0.5 on 2018-05-12 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('momotaro', '0002_auto_20180512_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='momotaro',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='momotaro.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.CharField(max_length=3, null=True, verbose_name='年代'),
        ),
    ]
