# Generated by Django 2.0.5 on 2018-05-17 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Momotaro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=255, verbose_name='目標')),
                ('limit', models.CharField(max_length=20, verbose_name='期限')),
                ('reason', models.CharField(max_length=255, null=True, verbose_name='目標を設定した理由')),
                ('additional_comments', models.TextField(max_length=500, null=True, verbose_name='自由記入欄')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
