# Generated by Django 2.0.5 on 2018-05-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_momotaro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='momotaro',
            name='reason',
            field=models.CharField(max_length=255, null=True, verbose_name='目標を達成したい理由'),
        ),
    ]
